Feedback edits
SU-UTB/web-ples-fe pull request #29
Opened 2024-01-29 17:17 UTC by WilloS88

2024-01-29 18:24 UTC, SedlarDavid approved these changes

2024-01-29 19:41 UTC, tomesfilip requested changes

2024-01-29 19:41 UTC, tomesfilip commented on src/components/hamburger/Sidebar.tsx
> +import React, { useState } from 'react';
no need to import React

2024-01-29 19:41 UTC, tomesfilip commented on src/components/cards/SupportCard.tsx
> +      <a href={link} target="_blank">
as it's a link of a 3rd party, I'd suggest to add this attribute to it `rel="noopener noreferrer"`

2024-01-29 19:41 UTC, tomesfilip commented on src/styles/index.css
> +@media (max-width: 640px) {
no need to use the media queries here, we have tailwind for that

2024-01-29 19:41 UTC, tomesfilip commented on src/styles/index.css
> +.underline {
there's class called `underline` in tailwind already, no need to recreate it here

2024-01-29 19:41 UTC, tomesfilip commented on src/components/sections/SupportProgramSection.tsx
> +    <Section id="doprovodný-program">
let's not use diacritics in ids, could be problematic

2024-01-29 19:41 UTC, tomesfilip commented on src/components/sections/TicketsSection.tsx
> +        <h2 className="text-2xl sm:text-3xl font-semibold uppercase font-numbers mb-4 mx-2">
do we need this mx? I think it was aligned already, now it would be a bit off and not aligned with the images down there

2024-01-29 19:41 UTC, tomesfilip commented on src/components/sections/AboutSection.tsx
> +  const [isMobile, setIsMobile] = useState(false);
no need to use hooks and states for this.

we can just use media queries directly in the className (`hidden desktop:block`)

2024-01-29 19:41 UTC, tomesfilip commented on src/components/hamburger/Sidebar.tsx
>                <a
let's create a separate SocialLink component for this

2024-01-29 19:41 UTC, tomesfilip commented on src/components/hamburger/Sidebar.tsx
> +              'o-plese',
would be nice to put these into the constants, so we can grab them directly from there, also the ids could be defined there (as numbers for example)

2024-01-29 19:41 UTC, tomesfilip commented on src/components/hamburger/Sidebar.tsx
> +  const handleLinkClick = (
here, we don't have to use events at all. we could directly pass the `href` value into this function. Basically, we can remove this function and just set the active item directly on click

2024-01-29 19:41 UTC, tomesfilip commented on src/components/hamburger/Sidebar.tsx
> +import './styles/index.css';
no need to import this, the index.css is imported in the parent root component index.tsx or App.tsx

2024-01-30 14:22 UTC, tomesfilip requested changes

2024-01-30 14:22 UTC, tomesfilip commented on src/components/hamburger/Sidebar.tsx
> +                onClick={(e) => handleLinkClick(e, item.id)}
remove the handleLinkClick function as I mentioned above and set the active item directly here

2024-01-30 14:22 UTC, tomesfilip commented on src/components/hamburger/SocLink.tsx
> +export const SocLink: React.FC<SocLinkProps> = ({ href, text, icon }) => {
let's be consistent here please, use the classic approach we have everywhere `export const Component = ({prop1, prop2, ..}: Props) =>` ...

2024-01-30 14:22 UTC, tomesfilip commented on src/styles/index.css
> +.multiSelectContainer li:hover {
can't we move this class right to the needed element and use it there via tailwind?

2024-01-30 14:54 UTC, tomesfilip approved these changes

2024-01-30 14:57 UTC, merged